version: '3.8'

services:
  mariadb:
    build: ./mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    networks:
      - inception

  wordpress:
    build: ./wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

  nginx:
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:

